-keep class com.what3words.ocr.components.models.* { *; }
-keep class retrofit2.Call { *; }
-keep class com.what3words.javawrapper.request.* { *; }
-keep class com.what3words.javawrapper.response.* { *; }
-keep class com.what3words.ocr.components.models.* { *; }
-keep class com.what3words.api.sdk.bridge.* { *; }
-dontwarn com.what3words.javasdk.**